micronaut:
    application:
        name: bookrecommendation
    server:
        port: 8080
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
endpoints:
  health:
    enabled: true
    sensitive: false
#tag::jaeger[]
tracing:
    jaeger:
        enabled: true
        sampler:
            probability: 1 # <1>
#end::jaeger[]